# Default values for kibana
replicaCount: 1

image:
  repository: docker.elastic.co/kibana/kibana
  tag: "8.5.1"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

# Kibana configuration
kibana:
  # Environment variables
  env:
    - name: "ELASTICSEARCH_HOSTS"
      value: "http://elasticsearch:9200"
    - name: "SERVER_HOST"
      value: "0.0.0.0"
    - name: "SERVER_PORT"
      value: "5601"
    - name: "LOGGING_QUIET"
      value: "false"

  # No config file - use environment variables only
  config: {}

# Service configuration
service:
  type: NodePort
  port: 5601
  targetPort: 5601
  nodePort: 30561
  annotations: {}

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: kibana.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Resource limits
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Security context
securityContext:
  fsGroup: 1000
  runAsUser: 1000

# Pod security context
podSecurityContext:
  fsGroup: 1000

# Liveness probe
livenessProbe:
  httpGet:
    path: /app/kibana
    port: 5601
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# Readiness probe
readinessProbe:
  httpGet:
    path: /app/kibana
    port: 5601
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# Autoscaling
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
