# Production ELK Stack Configuration
global:
  namespace: elk-demo

# Elasticsearch production configuration
elasticsearch:
  enabled: true
  replicaCount: 1
  
  image:
    repository: docker.elastic.co/elasticsearch/elasticsearch
    tag: "8.5.1"
    pullPolicy: IfNotPresent
  
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  
  persistence:
    enabled: true
    size: 20Gi
    storageClass: "standard"
  
  service:
    type: ClusterIP
    port: 9200

# Kibana production configuration
kibana:
  enabled: true
  replicaCount: 1
  
  image:
    repository: docker.elastic.co/kibana/kibana
    tag: "8.5.1"
    pullPolicy: IfNotPresent
  
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  
  service:
    type: NodePort
    port: 5601
    nodePort: 30561
  
  kibana:
    env:
      - name: "ELASTICSEARCH_HOSTS"
        value: "http://elk-stack-elasticsearch:9200"
      - name: "SERVER_HOST"
        value: "0.0.0.0"
      - name: "SERVER_PORT"
        value: "5601"
      - name: "LOGGING_QUIET"
        value: "false"
    
    config: {}
  
  elasticsearch:
    enabled: false
